from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
from transformers import (
    Qwen2VLProcessor,
    Qwen2VLForConditionalGeneration,
    AutoProcessor,
    AutoModel,
    AutoTokenizer,
)
from typing import List
from qwen_vl_utils import process_vision_info
from enum import Enum, auto
import json
import requests
import time
device = 'cuda:0'

class CheckModel(Enum):
    qwen_turbo = auto()
    gpt_4o_mini = auto()
    
    @staticmethod
    def from_string(s: str):
        try:
            return CheckModel[s]
        except KeyError:
            raise ValueError()
        
    def check_qwen_turbo(self,top_captions,image_caption,relative_caption,openai_key,modified_caption:str='',max_length = 800)->str:
        prompt = f'''
        Assume you are an experienced composed image retrieval expert, skilled at precisely generating new image descriptions based on a reference image's description and the user's modification instructions.
        You excel at creating modified descriptions that can retrieve images matching the user's requested changes through vector retrieval.
        Your task is to help improve the effectiveness of compositional image retrieval by generating precise modification suggestions that will assist another large language model (LLM) in producing a better image description.
        Please note that this LLM has received the reference image's description and the user's modification instructions, and already generated a modified description.
        Moreover, a retrieval has been performed based on this modified description. Thus your task is to analyze the last retrieval result and provide modification suggestions and please follow the below steps to finish this task.
        First Step: Identifying Modifications
        Your first task is to identify the modifications and generate corresponding modification phrases.
        Specifically, here is the description of the reference image: "{image_caption}." Here are the user's modification requests: "{relative_caption}"
        By deeply understanding the image description and the user's modifications, please generate the following two types of modification phrases:
        1. If the modification involves changing the characteristics of an entity in the original reference image, please specify the changes,
        2. If the modification involves adding or deleting an entity, please specify the additions or deletions.
        Please note that the user's modifications may lack a subject; in such cases, infer and supply the object corresponding to the modification.
        Only include modifications explicitly mentioned by the user. If a certain type of modification is not present, you do not need to provide it and should avoid generating unspecified content.

        Step 2: Analyzing the Top-{len(top_captions)} Retrieved Image 
        Compare the modification phrases identified in Step 1 with the description of the top-{len(top_captions)} retrieved image : "{top_captions}". Note that this retrieval is performed with the modified description generated by another LLM, which has been mentioned above.
        Determine if the retrieved image meets the user's modification instructions.
        If it matches after excluding subjective modifications (e.g., "casual," "relaxed"), respond with: "Good retrieval, no more loops needed."
        If there are unmet modification phrases, proceed to Step 3.

        Step 3: Providing Modification Suggestions 
        For any unmet modifications identified in Step 2, suggest creative and targeted changes to help the LLM regenerate an improved and enhanced description. Provide innovative and imaginative suggestions to effectively guide the language model. Encourage unique and original responses to foster creativity while maintaining relevance and accuracy.
        '''
        final_result = ''
        url = "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
        headers = {
            'Content-Type': 'application/json; charset=utf-8',
            'Authorization': f'Bearer {openai_key}'
        }
        payload = {
            "model": "qwen-plus",
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": max_length,
            "temperature": 1.0
        }

    # Retry logic
        sleep_time = 0.25
        for _ in range(5):
            try:
                response = requests.post(url, headers=headers, json=payload)
                
                if response.status_code != 200:
                    print(f"Error executing request: {response.status_code} - {response.text}")
                    final_result = "Error executing request"
                
                try:
                    response_data = response.json()
                    if 'error' in response_data:
                        error_message = response_data['error'].get('message', 'Unknown error occurred')
                        print(f"API Error: {error_message}")
                        final_result = f"API Error: {error_message}"
                    return response_data['choices'][0]['message']['content']
                
                except json.JSONDecodeError:
                    print("Failed to decode JSON response.")
                    final_result = "Error: Failed to decode JSON response."
                except KeyError:
                    print("Unexpected response format.")
                    final_result = "Error: Unexpected response format."
            
            except requests.RequestException as e:
                print(f"Request failed: {e}")
                final_result = "Request error!"
            
            time.sleep(sleep_time)
            sleep_time = sleep_time * 2
        return final_result
    
    def chat_gpt_4o_mini(self,top_captions,image_caption,relative_caption,openai_key,modified_caption:str='',max_length = 800)->str:
        prompt = f'''
        Assume you are an experienced composed image retrieval expert, skilled at precisely generating new image descriptions based on a reference image's description and the user's modification instructions.
        You excel at creating modified descriptions that can retrieve images matching the user's requested changes through vector retrieval.
        Your task is to help improve the effectiveness of compositional image retrieval by generating precise modification suggestions that will assist another large language model (LLM) in producing a better image description.
        Please note that this LLM has received the reference image's description and the user's modification instructions, and already generated a modified description.
        Moreover, a retrieval has been performed based on this modified description. Thus your task is to analyze the last retrieval result and provide modification suggestions and please follow the below steps to finish this task.
        First Step: Identifying Modifications
        Your first task is to identify the modifications and generate corresponding modification phrases.
        Specifically, here is the description of the reference image: "{image_caption}." Here are the user's modification requests: "{relative_caption}"
        By deeply understanding the image description and the user's modifications, please generate the following two types of modification phrases:
        1. If the modification involves changing the characteristics of an entity in the original reference image, please specify the changes,
        2. If the modification involves adding or deleting an entity, please specify the additions or deletions.
        Please note that the user's modifications may lack a subject; in such cases, infer and supply the object corresponding to the modification.
        Only include modifications explicitly mentioned by the user. If a certain type of modification is not present, you do not need to provide it and should avoid generating unspecified content.

        Step 2: Analyzing the Top-{len(top_captions)} Retrieved Image 
        Compare the modification phrases identified in Step 1 with the description of the top-{len(top_captions)} retrieved image : "{top_captions}". Note that this retrieval is performed with the modified description generated by another LLM, which has been mentioned above.
        Determine if the retrieved image meets the user's modification instructions.
        If it matches after excluding subjective modifications (e.g., "casual," "relaxed"), respond with: "Good retrieval, no more loops needed."
        If there are unmet modification phrases, proceed to Step 3.

        Step 3: Providing Modification Suggestions 
        For any unmet modifications identified in Step 2, suggest creative and targeted changes to help the LLM regenerate an improved and enhanced description. Provide innovative and imaginative suggestions to effectively guide the language model. Encourage unique and original responses to foster creativity while maintaining relevance and accuracy.
        '''
        final_result = ''
        # url = 'https://api.openai.com/v1/chat/completions'
        url = 'https://forward.ronpay.org/v1/chat/completions'
        headers = {
            'Content-Type': 'application/json; charset=utf-8',
            'Authorization': f'Bearer {openai_key}'
        }
        payload = {
            # "model": "gpt-3.5-turbo",  
            "model": "gpt-4o-mini",
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": max_length,
            "temperature": 1.0
        }

    # Retry logic
        sleep_time = 0.25
        for _ in range(5):
            try:
                response = requests.post(url, headers=headers, json=payload)
                if response.status_code != 200:
                    print(f"Error executing request: {response.status_code} - {response.text}")
                    final_result = "Error executing request"
                try:
                    response_data = response.json()
                    if 'error' in response_data:
                        error_message = response_data['error'].get('message', 'Unknown error occurred')
                        print(f"API Error: {error_message}")
                        final_result = f"API Error: {error_message}"
                    return response_data['choices'][0]['message']['content']
                
                except json.JSONDecodeError:
                    print("Failed to decode JSON response.")
                    final_result = "Error: Failed to decode JSON response."
                except KeyError:
                    print("Unexpected response format.")
                    final_result = "Error: Unexpected response format."
            
            except requests.RequestException as e:
                print(f"Request failed: {e}")
                final_result = "Request error!"
            
            time.sleep(sleep_time)
            sleep_time = sleep_time * 2
        return final_result
        